name: CI
on: 
  schedule:
    - cron: '0 * * * *'
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --silent

      - uses: actions/cache@v2
        name: Setup Yarn build cache
        id: yarn-build-cache
        with:
          path: packages/**/dist
          key: ${{ runner.os }}-yarn-build-${{ hashFiles('packages/') }}
          restore-keys: |
            ${{ runner.os }}-yarn-build-

      - name: Yarn build without cache
        if: steps.yarn-build-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Cypress run
        run: yarn ci:test:replay
        env:
          RECORD_ALL_CONTENT: 1
          RECORD_REPLAY_METADATA_FILE: /tmp/replay-metadata

      - name: Upload replays
        if: ${{ always() }}
        uses: replayio/action-upload@v0.4.6
        with:
          api-key: rwk_5LiZGrCNbhfhsRZDHBD7kNoHd0gPqWg0SK82jUd5Cw8
